name: Build and publish Fun.LightFrom.Fable

on:
  push:
    paths:
    - 'src/Fun.LightForm.Fable/**'
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/Fun.LightForm.Fable/Fun.LightForm.Fable.fsproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
