name: Build and publish Fun.LightFrom.React

on:
  push:
    paths:
    - 'src/Fun.LightForm.React/**'
    - '.github/workflows/Build and publish Fun.LightFrom.React.yml'
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Try to bundle
      run: dotnet fsi Build.fsx -t BundleClient
      
    - name: Test
      run: dotnet run --project samples/Sample2/Sample2.fsproj
      
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/Fun.LightForm.React/Fun.LightForm.React.fsproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
